### ISSUE TITLE
Search page doesn't work on mobile

### ISSUE THREAD

**Issue by nickmonad** [nickmonad/bips.dev#1]
While testing on iOS mobile Brave and Safari, I noticed that the search page doesn't load search results via JS. Something about the `search.js` `initSearch()` function isn't allowing the HTML to change dynamically on mobile.

**Comment by nickmonad** [comment]
https://github.com/nickmonad/bips-dev/blob/master/web/static/search.js

**Comment by nickmonad** [comment]
^ token airdrop spam

**Comment by Pappyskull1** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!GreenCandlePrinter, @jonnydubowsky, @theinzanoo, @mina19872, @mypham1993, @JMrtzsn, @Rithdoc, @zruijie, @NukeManDan, @vougue, @yooml, @bmorelax, @fpcfjf, @vuiets, @ewakramo, @karbon0x, @bluedigits, @fanzai0311, @lemonnight, @kingdido999

**Comment by renato71amorim** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 6, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
euronomos, @muellerberndt, @afurculita, @aiaiaixxj, @ScottONeal, @tmd8886, @vivax98, @Mahdikarampoor, @Hxixing, @artificialkiwi, @neuralbayes, @Priori-Incantatem, @Cleideomargonsalves, @jchintu, @broqdev, @taariq, @qinix, @axlmozila2018, @klgt, @tylerdurden793

**Comment by NukeManDan** [comment]
FYI if you copy the think to the comment, and then open the user profile & hit `report` you can find a option for crypto scam & paste the comment link in the form. they kill off the accounts in a day or so, so they can't keep spamming.

**Comment by nickmonad** [comment]
@NukeManDan Thanks - you're right, I need to report them. This one is particular was "Job offer from Microsoft" spam, and I tried to hit "I don't see my issue" when I went to the reporting page, and it didn't let me continue the form, so I don't know if I hit a bug or temporary downtime or what. In any case, I will make sure to report in the future

**Comment by nickmonad** [comment]
This should be working! If you try to search on mobile and it doesn't work for some reason, please reply with your mobile browser and version so I can investigate.
